### ISSUE TITLE
libdashplayer/libmediaplayerservice: build error after cherry-picked commits (UTF16_to_UTF8 length computation and bound check)

### ISSUE THREAD

**Issue by nikolaoskalomiris** [CyanogenMod/android_external_mm-dash#1]
![error](https://cloud.githubusercontent.com/assets/17672938/18512392/8da42a78-7a91-11e6-85a8-2c317090d1f6.png)
I'm getting errors when compiling external/mm-dash/libdashplayer with cherry-picked commits from yesterday.

Commits:
https://github.com/CyanogenMod/android_system_core/commit/2cdbe550a6739966b0237a27e4660169a59f2662
(DO NOT MERGE libutils/Unicode.cpp: Correct length computation and add checks for utf16->utf8)
https://github.com/CyanogenMod/android_frameworks_av/commit/9b5caa8d9ee6cfd96793e9a60acc0448ab6be08a
(DO NOT MERGE libmediaplayerservice: Add bound checks to utf16_to_utf8)

Hope that I will help bring up the solution to this.

**Comment by ontherunvaro** [comment]
Can confirm, happens to me as well after a repo sync.

**Comment by ontherunvaro** [comment]
I have submitted a fix for review: https://review.cyanogenmod.org/#/c/162471/

**Comment by AlvaroBrey** [comment]
This has been solved by https://github.com/CyanogenMod/android_external_mm-dash/commit/9fb679d224768d1017e3e2685a52d08368daafc4
